apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

namespace: contextual-intelligence-dev

commonLabels:
  environment: development

patches:
  - path: replicas-patch.yaml

images:
  - name: ${DOCKER_REGISTRY}/contextual-intelligence
    newName: ${DOCKER_REGISTRY}/contextual-intelligence
    newTag: latest